### ISSUE TITLE
Segmentation fault after some minutes

### ISSUE THREAD

**Issue by lukasbableck** [sleequid/tidalRPC#5]
Hey,
for me the program always crashes after about 1 to 5 minutes with a segmentation fault.

macOS 11.4

**Discord version**
Canary 86601 (7f917ed)
Host 0.0.271
OS X 11.0.0 (20.5.0)

**Tidal version**
2.28.0.275

**Console output**
https://i.manchmal.online/tFiLD9U5.png

**Comment by ririxidev** [comment]
I'm wondering if there is still issue with `node-window-manager` package. I will try to look into it, because like always - electron won't give me a lot of info :////

**Comment by ririxidev** [comment]
Hey again,
I couldn't reproduce issue on my environment. I started `tidalRPC` from console like you.
Could you provide more info? It will be useful!

Environment:
macOS Big Sur - 11.4 (20F71)
Tidal 2.28.0.275 (W: 2021.05.19-15-cd0889fb089b15ffb7b504a3667708bd0a40e9b8) (NP: 3.0.5.39)
iTerm 2 Build 3.4.6

**Comment by lukasbableck** [comment]
I don't really know what other info I can give.
I'm also using iTerm 2, Build 3.4.8 though, but I don't think this could be an issue because it also crashes if I just run the .app normally. That's why I ran it from the terminal initially.
I'm have the same macOS and Tidal version as you.

Oh and it happens mid-playback, so no pausing/resuming/skipping.

**Comment by ririxidev** [comment]
Yeah - same, that's really odd issue. I will try everything I can to reproduce this issue 😄

**Comment by ririxidev** [comment]
@lukasbableck are you using M1 mac or Intel one?

**Comment by lukasbableck** [comment]
> @lukasbableck are you using M1 mac or Intel one?

Intel

**Comment by ririxidev** [comment]
I'm going to push new version soon - It will have sentry to handle crashing errors so I *hope* I will have better view on your error when you will get it. I'm really sorry for that but I just can't reproduce it on my macOS even macOS 12.

**Comment by ririxidev** [comment]
I will release new version in a bit; d14c453787336e24c0f359ade2e56c987779da80 this commit is regarding sentry so I hope in new version we will get more info about your issue 😄

**Comment by ririxidev** [comment]
I released new version; Please try getting this error with this version: https://github.com/sleequid/tidalRPC/releases/tag/1.3.0

**Comment by lukasbableck** [comment]
The new version crashes instantly because of a 404 error. The path to the latest-mac.yml is wrong.

https://i.manchmal.online/sdbjeOyw.png

**Comment by ririxidev** [comment]
My bad hahahah forgot to add `v` to version branch 😂  Try now

**Comment by lukasbableck** [comment]
Ok still crashes. This time I tried it on my MacBook Pro (Intel), same macOS and Tidal version as previously, only my Discord version is newer now.

Here is the console output: https://i.manchmal.online/feGhR3T.txt

**Comment by ririxidev** [comment]
Can you show me what permissions did you give to tidalRPC and what happens after running it with sudo?

**Comment by ririxidev** [comment]
Should be fixed in https://github.com/ririxidev/node-window-manager/commit/80cef08e27a23f350384ab67fb72bed21577d61b & https://github.com/sleequid/tidalRPC/commit/f94e5cf9cb966acb93a0c07963229d1b3b6f3f97

**Comment by ririxidev** [comment]
For now, issue is going to be on hold since I need to code my own `node-window-manager`. I'm sorry for this issue and will try to do fix it in next few days.

**Comment by ririxidev** [comment]
Closing because of dropping Tidal services.
